# User.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, password:Faker::Internet.password)
# Meeting.create!(title: Faker::Nation.capital_city, date_time: Faker::Time.between(DateTime.now + 1, DateTime.now+20))
# UserMeeting.create(user_id: 7, meeting_id: 16, start_latitude: 51.53289 , start_longitude: -0.13096 ,user_status: "created")
# UserMeeting.create(user_id: 8, meeting_id: 16, start_latitude: 51.48881 , start_longitude: -0.22293 ,user_status: "invited")
# UserMeeting.create(user_id: 9, meeting_id: 16, start_latitude: 51.52612 , start_longitude: -0.10722 ,user_status: "declined")
